# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

first_value = 1
second_value = 1
fibonacci = 0
problem_2_solution = 0

while fibonacci < 4000000 do
  fibonacci = first_value + second_value
  if fibonacci % 2 == 0
    problem_2_solution += fibonacci
  end
  first_value == second_value
  second_value == fibonacci
end

puts problem_2_solution
